parameters:
    # Common hyperparameters
    name: 'FNN_warehouse'
    env_type: 'warehouse'
    time_horizon: 8
    # todo should actually be 32
    num_frames: 8
    # This should also probably be multiplied by 4
    obs_size: 584
    # MAIN MODEL
    # Fully connected module
    fully_connected: true
    num_fc_layers: 2
    num_fc_units: [640, 256]
    # Convolutional module
    convolutional: false
    # Recurrent module
    recurrent: false

    # INFLUENCE MODEL
    influence: false