parameters:
    # Common hyperparameters
    name: 'FNN_warehouse'
    env_type: 'warehouse'
    num_frames: 32
    # MAIN MODEL
    num_fc_layers: 2 # param not used
    num_fc_units: [640, 256]
    # Convolutional module
    convolutional: false # param not used
    # Recurrent module
    recurrent: false # param not used

    # INFLUENCE MODEL
    influence: false