parameters:
    # Common hyperparameters
    name: 'InfluenceNet_warehouse'
    env_type: 'warehouse'
    time_horizon: 8
    # MAIN MODEL
    # Fully connected module
    fully_connected: true
    num_fc_layers: 2
    num_fc_units: [576, 256]
    # Convolutional module
    convolutional: false
    # Recurrent module
    recurrent: false

    # INFLUENCE MODEL
    influence: true
    # Attention
    attention: false
    automatic_dpatch: false
    manual_dpatch: true
    # D-set
    inf_num_predictors: 25
    dset: [0, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62,
           63, 64, 65, 66, 67, 68, 69, 70, 71, 72]
    inf_num_rec_units: 64
    inf_seq_len: 8
