parameters:
    # Common hyperparameters
    name: 'RNN_warehouse'
    env_type: 'warehouse'
    time_horizon: 8
    # MAIN MODEL
    # Fully connected module
    fully_connected: true
#    num_fc_units: [640]  # param not used
    # Convolutional module
    convolutional: false
    # Recurrent module
    recurrent: true
#    num_rec_units: 256  # param not used
    seq_len: 8
    # INFLUENCE MODEL
    influence: false
