parameters:
    # Common hyperparameters
    mode: 'train'
    name: 'FNN'
    env_type: 'sumo' # 'atari', 'SUMO', or 'gridworld'
    scene: 'loop_network'
    max_steps: 2.0e+6
    obs_type: 'vector'
    obs_size: 960
    max_episode_steps: 250
    summary_frequency: 5.0e+4
    num_frames: 32

    # MAIN MODEL
    # Fully connected module
    fully_connected: true
    num_fc_layers: 2
    num_fc_units: [256, 64]
    # Convolutional module
    convolutional: false
    # Recurrent module
    recurrent: false

    # INFLUENCE MODEL
    influence: false

